name: Empty Commit Push

on:
  schedule:
    - cron: '0 */10 * * *'  # 每 10 小時執行一次
  workflow_dispatch: {}   # 允許手動觸發

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 確保有寫入權限
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Create Empty Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "chore: empty commit [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
